### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by edgan** [satya164/warn-once#1]
I don't see any license file. Can one be decided on and added to the repository? Would a PR help?

Here is a quote from the license. It is generally interpreted as a copy of the license in the git repository, and in any downloaded copies of the code like from npm or yarn.

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by satya164** [comment]
It's MIT: https://github.com/satya164/warn-once/blob/514e9993ba7c1c113dbeda7242d5260cb4216654/package.json#L9

Feel free to send a PR with license file

**Comment by emmahsax** [comment]
@satya164 Here's a PR: https://github.com/satya164/warn-once/pull/2
